package main


var ag AutoGenerated
var days Days
var subject Subject
var lessons Lessons
var hours Hours

type AutoGenerated struct {
	Days     []Days   `json:"days"`
	ChatStub ChatStub `json:"chatStub"`
}
type Hours struct {
	StartHour   string `json:"startHour"`
	StartMinute string `json:"startMinute"`
	EndHour     string `json:"endHour"`
	EndMinute   string `json:"endMinute"`
}
type Subject struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	KnowledgeArea string `json:"knowledgeArea"`
}
type Lessons struct {
	ID             string        `json:"id"`
	Number         int           `json:"number"`
	Place          string        `json:"place"`
	StartTime      string        `json:"startTime"`
	EndTime        string        `json:"endTime"`
	Hours          Hours         `json:"hours"`
	IsCanceled     bool          `json:"isCanceled"`
	Theme          string        `json:"theme"`
	MeetingURL     interface{}   `json:"meetingUrl"`
	Subject        Subject       `json:"subject"`
	ImportantWorks []interface{} `json:"importantWorks"`
	Homework       interface{}   `json:"homework"`
	HasAttachment  bool          `json:"hasAttachment"`
	WorkMarks      []interface{} `json:"workMarks"`
	IsEmpty        bool          `json:"isEmpty"`
	Comment        interface{}   `json:"comment"`
}
type Days struct {
	Date                 string      `json:"date"`
	UtcOffset            int         `json:"utcOffset"`
	HasImportantWork     bool        `json:"hasImportantWork"`
	DayHomeworksProgress interface{} `json:"dayHomeworksProgress"`
	Lessons              []Lessons   `json:"lessons"`
}
type ChatStub struct {
	Jid string `json:"jid"`
}